# Generated by Django 4.2 on 2023-04-28 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_alter_user_id_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id_rol',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
    ]
