# Generated by Django 4.2 on 2023-04-30 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_remove_user_id_rol_alter_user_email_delete_rol'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
