# Generated by Django 4.2 on 2023-04-30 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
