# Generated by Django 4.2 on 2023-05-06 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0007_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programas',
            name='id_usuarios',
        ),
        migrations.RemoveField(
            model_name='proyeccion',
            name='id_asignatura',
        ),
        migrations.RemoveField(
            model_name='proyeccion',
            name='id_programas',
        ),
        migrations.DeleteModel(
            name='Asignatura',
        ),
        migrations.DeleteModel(
            name='Programas',
        ),
        migrations.DeleteModel(
            name='Proyeccion',
        ),
    ]
