# Generated by Django 4.2 on 2023-05-06 02:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inicio', '0008_remove_programas_id_usuarios_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=200)),
                ('nombre', models.CharField(max_length=200)),
                ('creditos', models.IntegerField()),
                ('intensidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Programas',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('correo', models.CharField(max_length=200)),
                ('jornada', models.CharField(max_length=200)),
                ('id_usuarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Proyeccion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_asignatura', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inicio.asignatura')),
                ('id_programas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.programas')),
            ],
        ),
    ]
