# Generated by Django 4.2 on 2023-05-06 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0010_mensaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='leido',
        ),
        migrations.AddField(
            model_name='mensaje',
            name='archivo_adjunto',
            field=models.FileField(blank=True, null=True, upload_to='archivos_adjuntos/'),
        ),
    ]
