# Generated by Django 4.2 on 2023-05-07 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0012_proyeccion_num_profesores_proyeccion_total_semana'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyeccion',
            name='semestre',
            field=models.IntegerField(default=1),
        ),
    ]
