# Generated by Django 4.2 on 2023-05-13 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0018_disponibilidad'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Disponibilidad',
        ),
    ]
