# Generated by Django 4.2 on 2023-05-13 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0021_alter_disponibilidad_comentarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidad',
            name='comentarios',
            field=models.TextField(default='Disponible', null=True),
        ),
    ]
