# Generated by Django 4.2 on 2023-05-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0024_restriccion_alter_programacion_dia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidad',
            name='fecha',
            field=models.CharField(choices=[('LUNES', 'Lunes'), ('MARTES', 'Martes'), ('MIERCOLES', 'Miércoles'), ('JUEVES', 'Jueves'), ('VIERNES', 'Viernes'), ('SABADO', 'Sábado'), ('DOMINGO', 'Domingo')], max_length=15),
        ),
        migrations.AlterField(
            model_name='disponibilidad',
            name='hora_fin',
            field=models.CharField(choices=[('10:00', '10:00 AM'), ('13:00', '01:00 PM'), ('17:00', '05:00 PM'), ('18:30', '06:30 PM'), ('21:30', '09:30 PM')], max_length=5),
        ),
        migrations.AlterField(
            model_name='disponibilidad',
            name='hora_inicio',
            field=models.CharField(choices=[('07:00', '07:00 AM'), ('10:00', '10:00 AM'), ('14:00', '02:00 PM'), ('17:00', '05:00 PM'), ('18:30', '06:30 PM')], max_length=5),
        ),
    ]
