# Generated by Django 4.2 on 2023-05-24 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0025_alter_disponibilidad_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibilidad',
            name='mostrar_en_tabla',
            field=models.BooleanField(default=True),
        ),
    ]
