# Generated by Django 4.2 on 2023-05-25 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0026_disponibilidad_mostrar_en_tabla'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Programacion',
        ),
    ]
