# Generated by Django 4.2 on 2023-05-25 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inicio', '0028_programacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='programacion',
            name='user',
            field=models.ForeignKey(default=12345, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
