# Generated by Django 4.2 on 2023-05-25 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0029_programacion_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Programacion',
        ),
    ]
