# Generated by Django 4.2 on 2023-05-25 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0031_programacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programacion',
            old_name='user',
            new_name='id_usuarios',
        ),
    ]
