# Generated by Django 4.2 on 2023-05-25 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0032_rename_user_programacion_id_usuarios'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Programacion',
        ),
    ]
