# Generated by Django 4.2 on 2023-05-25 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0036_programacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Programacion',
        ),
    ]
