# Generated by Django 4.2 on 2023-05-26 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0038_programacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Programacion',
        ),
    ]
