# Generated by Django 4.2 on 2023-05-26 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0040_programacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programas',
            name='id_usuarios',
        ),
    ]
