# Generated by Django 4.2 on 2023-05-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0041_remove_programas_id_usuarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='programas',
            name='cod',
            field=models.CharField(default='0000', max_length=200),
        ),
    ]
