# Generated by Django 4.2 on 2023-05-26 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inicio', '0043_alter_programas_cod'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cronograma',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('semana', models.IntegerField()),
                ('fecha', models.DateField()),
                ('contenido_tematico', models.TextField()),
                ('material_apoyo', models.TextField()),
                ('observaciones', models.TextField()),
                ('chequeo', models.BooleanField(default=False)),
                ('id_usuarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
