# Generated by Django 4.2 on 2023-05-27 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0044_cronograma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronograma',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
