# Generated by Django 4.2 on 2023-06-03 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inicio', '0046_cronograma_mostrar_en_tabla'),
    ]

    operations = [
        migrations.AddField(
            model_name='programas',
            name='tecnico_apoyo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programas', to=settings.AUTH_USER_MODEL),
        ),
    ]
