# Generated by Django 4.2 on 2023-06-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0048_asistencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='noAsistio',
            field=models.BooleanField(default=False),
        ),
    ]
