# Generated by Django 4.2 on 2023-06-23 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0051_salones'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='salon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inicio.salones'),
        ),
    ]
