# Generated by Django 4.2 on 2023-06-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0054_alter_cronograma_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='tema_clase',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
